### ISSUE TITLE
Make configuration more intuitive

### ISSUE THREAD

**Issue by gnumpi** [gnumpi/esphome_audio#20]
The current configuration schema for ADF pipeline components is not intuitive and primarily focuses on the developer's perspective rather than the user's perspective.

I am planing the following changes:
- [ ] rename adf_pipeline section to adf_pipeline_element
- [ ] refer pipeline element type from the actual component implementation if possible
- [ ] move the source and sink elements from the pipeline configuration to separate config parameter
- [ ] use pipeline config parameter for optional elements in between source and sink only
 
old config:
```yaml
adf_pipeline:
  - platform: i2s_audio
    type: sink
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO10

  - platform: i2s_audio
    type: source
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO4
    channel: left
    sample_rate: 16000
    bits_per_sample: 16bit
    
  - platform: audio_processing
    type: resample-filter
    id: downsample

microphone:
  - platform: adf_pipeline
    id: adf_microphone
    pipeline:
      - adf_i2s_in
      - self

speaker:
  - platform: adf_pipeline
    id: adf_speaker
    pipeline:
      - self
      - adf_i2s_out


media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: s3-dev_media_player
    internal: false
    pipeline:
      - self
      - downsample
      - adf_i2s_out
```

new config: 

```yaml
adf_pipeline_element:
  - platform: i2s_audio
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO10

  - platform: i2s_audio
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO4
    channel: left
    sample_rate: 16000
    bits_per_sample: 16bit
  
  - platform: audio_processing
    type: resample-filter
    id: downsample


microphone:
  - platform: adf_pipeline_element
    id: adf_microphone
    source: adf_i2s_in
    
speaker:
  - platform: adf_pipeline_element
    id: adf_speaker
    sink: adf_i2s_out    

media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: s3-dev_media_player
    internal: false
    sink: adf_i2s_out
    pipeline:
      - downsample
```

Any comments or suggestions on this?

**Comment by nielsnl68** [comment]
Maybe it can simpler (basically what you already have. without the *self*):

```yaml
microphone:
  - platform: adf_audio
    id: adf_microphone
    source:
        - downsample
        - adf_i2s_in
         
speaker:
  - platform: adf_audio
    id: adf_speaker
    destiny: 
        - downsample
        - adf_i2s_out
 
```
