### ISSUE TITLE
Resampler on input doesn't work in duplex mode

### ISSUE THREAD

**Issue by jherby2k** [gnumpi/esphome_audio#42]
Per https://github.com/gnumpi/esphome_audio/issues/17, in duplex mode we have to use 16000 Hz and skip the resampler if we want the mic to work. This means poor output audio quality, of course.

**Comment by gnumpi** [comment]
Could you try with this branch if 44.1kHz is working with Onju?
please make sure to set both i2s pipeline elements to 44.1kHz and add the resampler to the mic pipeline.

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: fix_mic_resampler
    components: [ adf_pipeline, i2s_audio ]
```
please share your logs if it is not working.
