### ISSUE TITLE
Media player repeats last played sound after each TTS response, if wasn't stopped explicitly

### ISSUE THREAD

**Issue by formatBCE** [gnumpi/esphome_audio#46]
IDK if it's something worth fixing, but as of now, on config with newly introduced timers from ESPHome, when i play "ding" for timer on media_player, and DON'T explicitly call "stop" on media_player after, each TTS response after that is accompanied with "ding" after. 
It looks like new status "ANNOUNCING" calls "PLAY" after announcement, regardless of previous player state (i assume it's paused there, probably, after timer's "ding"). 

Same thing happens, if i play anything on player from HA, let it play to the end, and then call some TTS - it will play< whatever was there before, after TTS. But doesn't happen, if i click "stop" button in HA while player is still playing.

**Comment by BigBobbas** [comment]
I added the below to `media_payer: `component as a workaround and this appears to work fine with this added as I was having the same behaviour.
```yaml
    on_idle:
      - media_player.stop 
  ```

**Comment by formatBCE** [comment]
> I added the below to `media_payer: `component as a workaround and this appears to work fine with this added as I was having the same behaviour.
> ```yaml
>     on_idle:
>       - media_player.stop 
>   ```

That's elegant. :)

**Comment by gnumpi** [comment]
Thanks for pointing at this, actually it should only call play if it was in playing state when the announcement started. The hint that it plays tracks that has already been finished playing, might be very helpful. Probably, I forgot reseting the state somewhere...

**Comment by gnumpi** [comment]
I might have found the problem, can you check if this fix (mp_reset_current_track_on_finish branch) helps?
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: mp_reset_current_track_on_finish
    components: [ adf_pipeline, i2s_audio ]
    refresh: 0s
```
