### ISSUE TITLE
With HA 2024.7 Local Intents (specifically setting timers via built in intents) are not working

### ISSUE THREAD

**Issue by admn-monkey** [gnumpi/esphome_audio#51]
Ultimately, I loaded the default ESP32-S3-Box-3 install via the Home Assistant instructions to test if it was related to the esphome_audio repo. With the HA ESPHOME default esp32-s3-box-3.yaml firmware the ESP32 works as expected with now built in timer via voice support. 

With the esphome_audio, it appears none of the built in intents are working. 

I will admit the voice recognition and audio capabilities are so much better with the esphome_audio load, but local intents are critical for ongoing functionality. 

Am I missing something obvious for how to make built in intents work with esphome_audio?

**Comment by gnumpi** [comment]
Can you be more specific with what is not working with esphome_audio? Could you provide configs and logs for that issue? Thx.

**Comment by formatBCE** [comment]
For me, timers are still working fine. After HA 2024.7.1 my yelling about having default intents overriding custom ones was heard and fixed, so now it tried to run my own timers logic. But when I disabled my custom intent for that, timers started working on device again.

**Comment by admn-monkey** [comment]
> For me, timers are still working fine. After HA 2024.7.1 my yelling about having default intents overriding custom ones was heard and fixed, so now it tried to run my own timers logic. But when I disabled my custom intent for that, timers started working on device again.

@formatBCE 

How did you disable your custom intents? Was that by just disabling the related automation(s)?

@gnumpi 

 I'm seeing this in my main HA logs when I ask the device "Start a _X_ minute timer":
 
 `2024-07-06 11:22:07.950 ERROR (MainThread) [homeassistant.components.conversation.default_agent] Intent handling error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 347, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 140, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/intent/timers.py", line 836, in async_handle
    raise TimersNotSupportedError(intent_obj.device_id)
homeassistant.components.intent.timers.TimersNotSupportedError: Device does not support timers: device_id=_xxxxxxxxxxxxxxxxxxxxxxxxxxx_`

**Comment by formatBCE** [comment]
@admn-monkey I just commented out the custom sentence part, and reloaded conversation in Dev tools.
But I suppose it's not your case, since your log is showing that device doesn't support timers. This happens, if you don't have at least on_timer_finished section in your voice_assistant config. I had it before.

**Comment by admn-monkey** [comment]
@gnumpi 

YAML for the device is attached. There's nothing special about this; outside an announcement speaker on response, it's nearly exactly default to yours. 

[ESP32Config_redacted.yaml.txt](https://github.com/user-attachments/files/16116778/ESP32Config_redacted.yaml.txt)

**Comment by formatBCE** [comment]
> @gnumpi 
> 
> YAML for the device is attached. There's nothing special about this; outside an announcement speaker on response, it's nearly exactly default to yours. 
> 
> [ESP32Config_redacted.yaml.txt](https://github.com/user-attachments/files/16116778/ESP32Config_redacted.yaml.txt)
> 
> 

Yup, as I said, add lambda to notify user on timer finished to VA, and it will work.

**Comment by admn-monkey** [comment]
> > @gnumpi
> > YAML for the device is attached. There's nothing special about this; outside an announcement speaker on response, it's nearly exactly default to yours.
> > [ESP32Config_redacted.yaml.txt](https://github.com/user-attachments/files/16116778/ESP32Config_redacted.yaml.txt)
> 
> Yup, as I said, add lambda to notify user on timer finished to VA, and it will work.

@formatBCE 

May I ask a favor? Could you copy in your on_timer_finished VA section from your device? 

The documentation on that section is somewhat lacking. Plus, after messing with this for 2 hours now, it's not even moderately easy to just take the section from the ESPHome firmware ESP32-S3-Box-3 yaml and integrate it with the esphome_audio yaml. While I did get it in there and sloppily working, my attempt isn't functional. It will start the timer, yet when it's finished I appear to be locking out the assist voice recognition state. 

@gnumpi 

I do think the issue remains open considering that the esphome_audio yaml does not contain the on_timer_finished section and the one from any of the standard esphome reference firmwares are not structurally compatible without considerable effort on the end user.

**Comment by formatBCE** [comment]
@admn-monkey i kept it simple and stupid:

```
on_timer_finished:
    - script.execute: stop_voice_assistant
    - lambda: id(voice_assistant_phase) = ${voice_assist_timer_finished_phase_id};
    - script.execute: draw_display
    - wait_until:
        not:
          microphone.is_capturing:
    - media_player.play_media: http://homeassistant.local/local/sounds/timer-ding.mp3
    - delay: 2s
    - media_player.play_media: http://homeassistant.local/local/sounds/timer-ding.mp3
    - delay: 2s
    - media_player.play_media: http://homeassistant.local/local/sounds/timer-ding.mp3
    - delay: 2s
    - wait_until:
        not:
          media_player.is_playing:
    - script.execute: start_voice_assistant
    - script.execute: draw_display
```
It's pretty close to official S3-Box firmware [here](https://github.com/esphome/firmware/blob/main/wake-word-voice-assistant/esp32-s3-box.yaml), but i decided to go with 3 "dings" instead of continuous dinging.

P.S. i don't think this is current repo's issue, as timers are additional functionality, and requires additional work outside of ESPHome.
