### ISSUE TITLE
How to use speaker.play ?

### ISSUE THREAD

**Issue by s00500** [gnumpi/esphome_audio#73]
Hey there, I tried to use this guide to create some data for speaker.play... but I could not make it sound at all...

https://esphome.io/guides/audio_clips_for_i2s.html

I am using the voice assistant with this and trying to get it to play a sound in the start. Cant make it work, but I am getting the wav audio response from the assist pipeline played... any idea or pointers ? (I am basically on the onju voice micro wake word config, with the speaker instead of media player)

Here is my audio config:

```
i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO13
    i2s_bclk_pin: GPIO18
    access_mode: duplex

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_dout_pin: GPIO12
    sample_rate: 16000
    adf_alc: true
    bits_per_sample: 32bit
    fixed_settings: true
    channel: left

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_shared
    i2s_din_pin: GPIO17
    channel: left
    pdm: false
    sample_rate: 16000
    bits_per_sample: 32bit
    fixed_settings: true

microphone:
  - platform: adf_pipeline
    id: onju_microphone
    keep_pipeline_alive: true
    gain_log2: 3
    pipeline:
      - adf_i2s_in
      - self

speaker:
  - platform: adf_pipeline
    id: onju_out
    keep_pipeline_alive: false
    pipeline:
      - self
      - resampler
      - adf_i2s_out
  ```
