### ISSUE TITLE
random speed of playback 

### ISSUE THREAD

**Issue by BigBobbas** [gnumpi/esphome_audio#8]
Hi, 
I am currently testing in ESPHome 2024.2.0 . with an ESP32-s3-N16R8. When I stream some mp3 files,  tts using piper or nabu casa and radio using 'radio browser' the playback speed varies from very fast to very slow with no obvious pattern, but never at the correct speed. If I play music mp3s from a dlna server the audio has been at the correct speed. 
any more details I can provide. I am more than happy to help, as this has been needed in ESPHome for a long time! 

Thanks for your help :)

**Comment by gnumpi** [comment]
Hey thanks for your testing. Today I uploaded a fix which probably addressed exactly that issue. Before that update, the number of channels and sampling rate where not always changed correctly when switching between audio sources. Could you try to test the latest version and report if the issue still occurs?

**Comment by gnumpi** [comment]
Ohhh no!!! Ok, thanks for reporting, I probably can look into it tomorrow.

**Comment by BigBobbas** [comment]
no problem, there is no hurry.

**Comment by gnumpi** [comment]
Could you share your config and which DAC you are using?

**Comment by BigBobbas** [comment]
DA is a MAX98357 and config below 

```
esphome:
  name: esp-idf
  platformio_options:
    board_build.flash_mode: dio
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: octal
  speed: 80MHz

logger:

ota:

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
api:
  on_client_connected: 
    - micro_wake_word.start

external_components:
  - source:
      type: local
      path: custom
    components: [ adf_pipeline, i2s_audio ]
    
button:
  - platform: restart
    id: reboot
    name: "Reboot"
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO5
    i2s_bclk_pin: GPIO6
  - id: i2s_out
    i2s_lrclk_pin: GPIO46
    i2s_bclk_pin: GPIO9

adf_pipeline:
  - platform: i2s_audio
    type: sink
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO10

  - platform: i2s_audio
    type: source
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO4
    channel: left
    sample_rate: 16000
    bits_per_sample: 16bit


microphone:
  - platform: adf_pipeline
    id: adf_microphone
    pipeline:
      - adf_i2s_in
      - self

#speaker:
#  - platform: adf_pipeline
#    id: adf_speaker
#    pipeline:
#      - self
#      - adf_i2s_out


media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: s3-dev_media_player
    internal: false
    pipeline:
      - self
      - adf_i2s_out
      
micro_wake_word:
  model: hey_jarvis
  on_wake_word_detected:  
      - media_player.play_media: http://192.168.1.8:8123/local/vad.mp3
      - voice_assistant.start:

  
voice_assistant:
  id: va
  microphone: adf_microphone
  media_player: adf_media_player
  noise_suppression_level: 2
  auto_gain: 16dBFS
  volume_multiplier: 6
  use_wake_word: false
  on_end:
      then:
        - wait_until:
            not:
              voice_assistant.is_running:
        - voice_assistant.stop
        - micro_wake_word.start:
```
