### ISSUE TITLE
ESPHome cannot resolve the nested platform in external components: adf_pipeline.speaker

### ISSUE THREAD

**Issue by wjohnson2250** [gnumpi/esphome_audio#83]
In the file tests/components/adf_pipeline/esp32-s3-va.yaml from the esphome_audio repository, the following section is commented out:

```yaml
  #- platform: speaker
  #  id: adf_speaker
  #  pipeline:
  #    - self
  #    - adf_i2s_out
```

Uncommenting it causes this error: Platform not found: 'adf_pipeline.speaker'

This is surprising because adf_pipeline/speaker is an official component in the repository.

I am currently working on a custom component based on adf_pipeline.speaker, and ran into the same issue.

**Comment by ffalsk** [comment]
Hi, I think you can use the official speaker component compatible with ESP-IDF.
Below is the official website about this component.
[i2s_audio](https://esphome.io/components/speaker/i2s_audio)
[speaker](https://esphome.io/components/media_player/speaker)

Here is my yaml config
```
i2s_audio:
    i2s_lrclk_pin: 5
    i2s_bclk_pin: 4

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: 10
    sample_rate: 44100

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    announcement_pipeline:
        speaker: speaker_id
        num_channels: 1
        format: WAV
```
